// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Round3;

namespace Round3.Migrations
{
    [DbContext(typeof(StatesContext))]
    partial class StatesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Round3.Models.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AdjustedIncome");

                    b.Property<double>("AverageAge");

                    b.Property<double>("AveragePopulation");

                    b.Property<double>("AverageSalary");

                    b.Property<double>("AverageTemp");

                    b.Property<double>("CostOfLiving");

                    b.Property<double>("GrowthRate");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("StateName");

                    b.Property<double>("TaxRate");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new { Id = -1, AdjustedIncome = 64417000.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 57244.0, AverageTemp = 67.6, CostOfLiving = 99.0, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Florida", TaxRate = 0.0 },
                        new { Id = -2, AdjustedIncome = 64417000.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 60325.0, AverageTemp = 67.6, CostOfLiving = 90.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Texas", TaxRate = 0.0 },
                        new { Id = -3, AdjustedIncome = 64417000.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 84390.0, AverageTemp = 67.6, CostOfLiving = 100.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Virginia", TaxRate = 0.0 },
                        new { Id = -4, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53707.0, AverageTemp = 67.6, CostOfLiving = 92.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Utah", TaxRate = 0.0 },
                        new { Id = -5, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 69697.0, AverageTemp = 67.6, CostOfLiving = 95.5, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Illinois", TaxRate = 0.0 },
                        new { Id = -6, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 73787.0, AverageTemp = 67.6, CostOfLiving = 91.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Wyoming", TaxRate = 0.0 },
                        new { Id = -7, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 69998.0, AverageTemp = 67.6, CostOfLiving = 88.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Michigan", TaxRate = 0.0 },
                        new { Id = -8, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 72055.0, AverageTemp = 67.6, CostOfLiving = 90.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Missouri", TaxRate = 0.0 },
                        new { Id = -9, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 71709.0, AverageTemp = 67.6, CostOfLiving = 90.4, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Kansas", TaxRate = 0.0 },
                        new { Id = -10, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 71223.0, AverageTemp = 67.6, CostOfLiving = 89.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Tennessee", TaxRate = 0.0 },
                        new { Id = -11, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 54398.0, AverageTemp = 67.6, CostOfLiving = 93.0, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Ohio", TaxRate = 0.0 },
                        new { Id = -12, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 69362.0, AverageTemp = 67.6, CostOfLiving = 94.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "North Carolina", TaxRate = 0.0 },
                        new { Id = -13, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 67282.0, AverageTemp = 67.6, CostOfLiving = 88.6, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Oklahoma", TaxRate = 0.0 },
                        new { Id = -14, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 68037.0, AverageTemp = 67.6, CostOfLiving = 102.1, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Colorado", TaxRate = 0.0 },
                        new { Id = -15, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 80595.0, AverageTemp = 67.6, CostOfLiving = 107.1, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Washington", TaxRate = 0.0 },
                        new { Id = -16, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 56129.0, AverageTemp = 67.6, CostOfLiving = 87.9, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Indiana", TaxRate = 0.0 },
                        new { Id = -17, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 66739.0, AverageTemp = 67.6, CostOfLiving = 89.6, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Idaho", TaxRate = 0.0 },
                        new { Id = -18, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 67696.0, AverageTemp = 67.6, CostOfLiving = 91.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Alabama", TaxRate = 0.0 },
                        new { Id = -19, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 65064.0, AverageTemp = 67.6, CostOfLiving = 98.1, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Arizona", TaxRate = 0.0 },
                        new { Id = -20, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 62715.0, AverageTemp = 67.6, CostOfLiving = 86.0, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Mississippi", TaxRate = 0.0 },
                        new { Id = -21, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 68966.0, AverageTemp = 67.6, CostOfLiving = 101.1, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Minnesota", TaxRate = 0.0 },
                        new { Id = -22, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 60514.0, AverageTemp = 67.6, CostOfLiving = 102.6, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Deleware", TaxRate = 0.0 },
                        new { Id = -23, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 64185.0, AverageTemp = 67.6, CostOfLiving = 102.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Pennsylvania", TaxRate = 0.0 },
                        new { Id = -24, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 60863.0, AverageTemp = 67.6, CostOfLiving = 134.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "California", TaxRate = 0.0 },
                        new { Id = -25, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 82260.0, AverageTemp = 67.6, CostOfLiving = 100.5, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "South Carolina", TaxRate = 0.0 },
                        new { Id = -26, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 62468.0, AverageTemp = 67.6, CostOfLiving = 91.4, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Georgia", TaxRate = 0.0 },
                        new { Id = -27, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 62756.0, AverageTemp = 67.6, CostOfLiving = 121.0, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "New Jersey", TaxRate = 0.0 },
                        new { Id = -28, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 104.5, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Nevada", TaxRate = 0.0 },
                        new { Id = -29, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 94.4, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Louisiana", TaxRate = 0.0 },
                        new { Id = -30, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 44725.0, AverageTemp = 67.6, CostOfLiving = 90.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Kentucky", TaxRate = 0.0 },
                        new { Id = -31, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53810.0, AverageTemp = 67.6, CostOfLiving = 125.0, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Maryland", TaxRate = 0.0 },
                        new { Id = -32, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 90.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Iowa", TaxRate = 0.0 },
                        new { Id = -33, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 71896.0, AverageTemp = 67.6, CostOfLiving = 135.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "New York", TaxRate = 0.0 },
                        new { Id = -34, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 95.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "New Mexico", TaxRate = 0.0 },
                        new { Id = -35, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 58434.0, AverageTemp = 67.6, CostOfLiving = 96.9, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Wisconsin", TaxRate = 0.0 },
                        new { Id = -36, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 119.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "New Hampshire", TaxRate = 0.0 },
                        new { Id = -37, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 98.9, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "North Dakota", TaxRate = 0.0 },
                        new { Id = -38, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 112.0, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Maine", TaxRate = 0.0 },
                        new { Id = -39, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 91.3, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Nebraska", TaxRate = 0.0 },
                        new { Id = -40, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 77321.0, AverageTemp = 67.6, CostOfLiving = 134.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Massachusetts", TaxRate = 0.0 },
                        new { Id = -41, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 102.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "South Dakota", TaxRate = 0.0 },
                        new { Id = -42, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 88.5, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Arkansas", TaxRate = 0.0 },
                        new { Id = -43, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 149.2, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "D.C.", TaxRate = 0.0 },
                        new { Id = -44, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 115.4, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Oregon", TaxRate = 0.0 },
                        new { Id = -45, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 100.8, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Montana", TaxRate = 0.0 },
                        new { Id = -46, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 62258.0, AverageTemp = 67.6, CostOfLiving = 130.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Connecticut", TaxRate = 0.0 },
                        new { Id = -47, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 122.4, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Vermont", TaxRate = 0.0 },
                        new { Id = -48, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 57342.0, AverageTemp = 67.6, CostOfLiving = 122.1, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Rhode Island", TaxRate = 0.0 },
                        new { Id = -49, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 53728.0, AverageTemp = 67.6, CostOfLiving = 131.6, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "Alaska", TaxRate = 0.0 },
                        new { Id = -50, AdjustedIncome = 64417.0, AverageAge = 43.0, AveragePopulation = 21310000.0, AverageSalary = 36806.0, AverageTemp = 67.6, CostOfLiving = 95.7, GrowthRate = 15.0, ImgUrl = "http://s3.amazonaws.com/wmfeimages/wp-content/uploads/2017/07/10162234/MAP-OF-FLORIDA-743x5001.png", StateName = "West Virginia", TaxRate = 0.0 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
